apiVersion: v1
kind: Service
metadata:
  name: game
spec:
  ports:
  - name: http
    port: 8888
  selector:
    app: game
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
spec:
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
       app: game
    spec:
      containers:
      - name: game
        image: gcr.io/devoxx19/game

