apiVersion: v1
kind: Service
metadata:
  name: ref
spec:
  ports:
  - name: http
    port: 8888
  selector:
    app: ref
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ref
spec:
  selector:
    matchLabels:
      app: ref
  template:
    metadata:
      labels:
        app: ref
    spec:
      containers:
      - name: ref
        image: gcr.io/devoxx19/ref

